version: 1
formatters:
  simple:
    format: '%(asctime)s - %(filename)s - %(funcName)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
  smtp_handler:
    class: logging.handlers.SMTPHandler
    level: ERROR
    formatter: simple
    mailhost: mail.cisco.com
    fromaddr: noreply@example.com
    toaddrs: [rakgupt3@cisco.com]
    subject: The Error log
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console,file_handler,smtp_handler]
    propagate: no
  noLogger:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
  errLogger:
    level: ERROR
    handlers: [smtp_handler]
    propagate: no
root:
  level: WARNING
  handlers: [console,file_handler]